# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dia Kharrat
email: dkharrat@gmail.com
description: >
  Official blog of Dia Kharrat, entrepreneur, technical advisor, and software engineer
baseurl: ""
url: "http://www.diakharrat.com"
twitter_username: dkharrat
github_username: dkharrat
linkedin_username: dkharrat

# Build settings
markdown: kramdown
